version: 2
jobs:
  build:
    docker:
      - image: python/3.5
    steps:
      - checkout
      - run:
          name: installing
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install .
      - run:
          name: Executing dry run
          command: |
              . venv/bin/activate
              skybeard -k FAKEKEY -c config.yml.example --dry-run
